### ISSUE TITLE
django-glitter-events broken by django-glitter and django-taggit

### ISSUE THREAD

**Issue by NeolithEra** [blancltd/django-glitter-events#30]
Hi, users are unable to run **_django-glitter-events_** due to dependency conflict with _**django**_ package. As shown in the following full dependency graph of **_django-glitter-events_**, **_django-glitter_** requires _**django <1.10,>=1.8**_，while **_django-taggit_** requires _**django >=1.11**_.

According to pip’s _“first found wins”_ installation strategy, _**django 1.9.13**_ is the actually installed version. However, _**django 1.9.13**_ does not satisfy _**>=1.11**_.

### Dependency tree-----------
```
django-glitter-events - 0.1.7
| +- django-glitter(install version:0.2.10 version range:*)
| | +- django(install version:1.9.13 version range:<1.10,>=1.8)
| | +- django-mptt(install version:0.10.0 version range:>=0.7)
| | | +- django(install version:3.0 version range:>=1.11)
| | | +- django-js-asset(install version:1.2.2 version range:*)
| | +- django-mptt-admin(install version:0.7.2 version range:>=0.3)
| | +- django-taggit(install version:1.1.0 version range:>=0.21.3)
| | | +- django(install version:3.0 version range:>=1.11)
| | +- python-dateutil(install version:2.8.1 version range:>=2.6.0)
| | +- sorl-thumbnail(install version:12.5.0 version range:>=12.2)
| +- django-taggit(install version:1.1.0 version range:>=0.21.3)
| | +- django(install version:3.0 version range:>=1.11)```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	 Fix your direct dependency to be **_django-taggit <=0.22.2, >=0.21.3_** and ask your upstream project **_django-glitter_** to fix its direct dependency to be **_django-taggit <=0.22.2, >=0.21.3_ **and** _django-mptt<=0.9.0_**.
2.	Ask your upstream project **_django-glitter_** to loose the version range of **_django_**.

@tomkinsWhich solution do you prefer, 1 or 2?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by tomkins** [comment]
Closing for the same reason as https://github.com/developersociety/django-glitter/issues/153

This project is deprecated.
